title:            Denis Sazonov
description:      Create like a god, command like a king, work like a slave!
disqus_shortname: sadensmol
url:             http://sadensmol.github.io

# Owner/author information
owner:
  name:           Denis Sazonov
  avatar:         bio-photo.jpg
  bio:            "Java/Kotlin developer"
  email:          sadensmol@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  upwork:         sadensmol
  fiverr:         sadensmol
  github:         sadensmol

  email:          sadensmol@gmail.com
  skype:          sadensmol
  telegram:       sadensmol

  linkedin:       sadensmol
  twitter:        sadensmol
  facebook:       sadensmol


  codesignal:     sadensmol
  hackerrank:     sadensmol
  stackexchange:
  instagram:
  flickr:         
  tumblr:

  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Moscow
future:      true
pygments:    true
markdown:    kramdown
